### ISSUE TITLE
Export will only let me export 1,000 users

### ISSUE THREAD

**Issue by simonwatt** [auth0-extensions/auth0-user-import-export-extension#36] opened 2018-07-16 01:41 UTC
The export functionality is only letting me choose the option 'EXPORT 1000 USERS', even though I have over 10,000 users on the tenant.

![user import export dashboard](https://user-images.githubusercontent.com/5018703/42740591-974d6b58-88fd-11e8-9d28-e84feb91c7f9.png)

Is there are a reason this is set at 1,000; is there a way that I can increase it?

**Comment by ShayMe21** [comment] 2018-08-29 01:16
Hello there,

The exported JSON file should include all your users as I have tested just now. The Export button does not accurately count/show 1000+ users it seems. This may be by design. I have contacted the dev team about this.

**Comment by fyockm** [comment] 2019-02-25 14:36
Fixed by #37. Button will now show "Export 1000+ Users".

**Closed by fyockm** 2019-02-25 14:36 UTC
